# alacritty config

import = ["~/.dotfiles/apps/alacritty/colours.gen.toml"]
live_config_reload = true

# env
[env]
TERM = "xterm-256color"

# window
[window]
padding = { x = 10, y = 8 }
startup_mode = "Maximized"
opacity = 0.88
dynamic_title = true

# font
[font]
size = 13.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[font.bold]
style = "Bold"

[font.italic]
style = "Oblique"

# selection
[selection]
save_to_clipboard = true

# scrolling
[scrolling]
history = 50000

# mouse
[[mouse.bindings]]
mouse = "Right"
action = "Paste"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[hints]
alphabet = "jfkdlsahgurieowpq"

[[hints.enabled]]
regex = "(mailto:|ssh://|https?://|ftp://|file://|www\\.)[\\w\\-@:%.+~#=/?&,;!()]*[\\w\\-@%+~#=/)]"
hyperlinks = true
command = { program = "xdg-open", args = [] }
post_processing = true
binding = { key = "O", mods = "Control|Shift" }

[hints.enabled.mouse]
enabled = true
mods = "Control"

# cursor
[cursor.style]
shape = "Block"
blinking = "On"
