# gpg-agent config

# security
no-allow-external-cache
no-allow-loopback-pinentry
# ignore-cache-for-signing
grab

# cache (8h)
default-cache-ttl 28800
max-cache-ttl 28800

# pinentry
pinentry-timeout 60
